# Generated by Django 2.0 on 2017-12-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverse_effects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credibility',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
