# Generated by Django 2.0 on 2017-12-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverse_effects', '0003_auto_20171226_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adverseeffect',
            old_name='bodypartID',
            new_name='bodypart',
        ),
        migrations.RenameField(
            model_name='adverseeffect',
            old_name='drugID',
            new_name='drug',
        ),
        migrations.RenameField(
            model_name='adverseeffect',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='tagID',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='blogID',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='userID',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commentID',
        ),
    ]
