# Generated by Django 2.0 on 2017-12-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverse_effects', '0004_auto_20171226_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='Test', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
